// Generated by gencpp from file mplus_ctrl/clear_imu.msg
// DO NOT EDIT!


#ifndef MPLUS_CTRL_MESSAGE_CLEAR_IMU_H
#define MPLUS_CTRL_MESSAGE_CLEAR_IMU_H

#include <ros/service_traits.h>


#include <mplus_ctrl/clear_imuRequest.h>
#include <mplus_ctrl/clear_imuResponse.h>


namespace mplus_ctrl
{

struct clear_imu
{

typedef clear_imuRequest Request;
typedef clear_imuResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct clear_imu
} // namespace mplus_ctrl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mplus_ctrl::clear_imu > {
  static const char* value()
  {
    return "cb827c3bb8c63dd8876ad66cc7f94518";
  }

  static const char* value(const ::mplus_ctrl::clear_imu&) { return value(); }
};

template<>
struct DataType< ::mplus_ctrl::clear_imu > {
  static const char* value()
  {
    return "mplus_ctrl/clear_imu";
  }

  static const char* value(const ::mplus_ctrl::clear_imu&) { return value(); }
};


// service_traits::MD5Sum< ::mplus_ctrl::clear_imuRequest> should match
// service_traits::MD5Sum< ::mplus_ctrl::clear_imu >
template<>
struct MD5Sum< ::mplus_ctrl::clear_imuRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mplus_ctrl::clear_imu >::value();
  }
  static const char* value(const ::mplus_ctrl::clear_imuRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mplus_ctrl::clear_imuRequest> should match
// service_traits::DataType< ::mplus_ctrl::clear_imu >
template<>
struct DataType< ::mplus_ctrl::clear_imuRequest>
{
  static const char* value()
  {
    return DataType< ::mplus_ctrl::clear_imu >::value();
  }
  static const char* value(const ::mplus_ctrl::clear_imuRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mplus_ctrl::clear_imuResponse> should match
// service_traits::MD5Sum< ::mplus_ctrl::clear_imu >
template<>
struct MD5Sum< ::mplus_ctrl::clear_imuResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mplus_ctrl::clear_imu >::value();
  }
  static const char* value(const ::mplus_ctrl::clear_imuResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mplus_ctrl::clear_imuResponse> should match
// service_traits::DataType< ::mplus_ctrl::clear_imu >
template<>
struct DataType< ::mplus_ctrl::clear_imuResponse>
{
  static const char* value()
  {
    return DataType< ::mplus_ctrl::clear_imu >::value();
  }
  static const char* value(const ::mplus_ctrl::clear_imuResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MPLUS_CTRL_MESSAGE_CLEAR_IMU_H
